<?php

// Register Custom Post Type

	$labels = array(
		'name'                  => _x( 'Podcasts', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Podcast', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Podcasts', 'text_domain' ),
		'name_admin_bar'        => __( 'Podcast', 'text_domain' ),
		'archives'              => __( 'Podcast Archives', 'text_domain' ),
		'attributes'            => __( 'Podcast Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Podcast:', 'text_domain' ),
		'all_items'             => __( 'All Podcasts', 'text_domain' ),
		'add_new_item'          => __( 'Add New Podcast', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Podcast', 'text_domain' ),
		'edit_item'             => __( 'Edit Podcast', 'text_domain' ),
		'update_item'           => __( 'Update Podcast', 'text_domain' ),
		'view_item'             => __( 'View Podcast', 'text_domain' ),
		'view_items'            => __( 'View Podcasts', 'text_domain' ),
		'search_items'          => __( 'Search Podcast', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Podcast', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Podcast', 'text_domain' ),
		'items_list'            => __( 'Podcasts list', 'text_domain' ),
		'items_list_navigation' => __( 'Podcasts list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Podcasts list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Podcast', 'text_domain' ),
		'description'           => __( 'An audio recording.', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'comments', 'revisions' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-microphone',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'podcast', $args );

